//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class quiniela {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal quiniela() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.quiniela", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $20.00 USD.
        /// </summary>
        internal static string BetAmount {
            get {
                return ResourceManager.GetString("BetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string BtnReg {
            get {
                return ResourceManager.GetString("BtnReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Points.
        /// </summary>
        internal static string CalcTitle {
            get {
                return ResourceManager.GetString("CalcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Last 20 Messages).
        /// </summary>
        internal static string ChatSubTitle {
            get {
                return ResourceManager.GetString("ChatSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message board.
        /// </summary>
        internal static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the 2014 FIFA Pool Site.
        /// </summary>
        internal static string ContentParagraph1 {
            get {
                return ResourceManager.GetString("ContentParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun and possibly win some money.
        /// </summary>
        internal static string ContentParagraph2 {
            get {
                return ResourceManager.GetString("ContentParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CurrenctExchange {
            get {
                return ResourceManager.GetString("CurrenctExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        internal static string DonationTitle {
            get {
                return ResourceManager.GetString("DonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact form not submitted!.
        /// </summary>
        internal static string FeedbackFailMsg {
            get {
                return ResourceManager.GetString("FeedbackFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact form submitted!.
        /// </summary>
        internal static string FeedbackSuccessMsg {
            get {
                return ResourceManager.GetString("FeedbackSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Code.
        /// </summary>
        internal static string FieldInvitation {
            get {
                return ResourceManager.GetString("FieldInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FieldMessage {
            get {
                return ResourceManager.GetString("FieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string FieldPin {
            get {
                return ResourceManager.GetString("FieldPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation PIN.
        /// </summary>
        internal static string FieldPinConfirmation {
            get {
                return ResourceManager.GetString("FieldPinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This field is required..
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This is not a valid email address..
        /// </summary>
        internal static string FieldValEmail {
            get {
                return ResourceManager.GetString("FieldValEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This is not a valid code..
        /// </summary>
        internal static string FieldValInviteCode {
            get {
                return ResourceManager.GetString("FieldValInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The message is too short..
        /// </summary>
        internal static string FieldValMessage {
            get {
                return ResourceManager.GetString("FieldValMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This is not a valid name..
        /// </summary>
        internal static string FieldValName {
            get {
                return ResourceManager.GetString("FieldValName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Not a valid PIN..
        /// </summary>
        internal static string FieldValPin {
            get {
                return ResourceManager.GetString("FieldValPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The PIN code is not a number or do not match..
        /// </summary>
        internal static string FieldValPin2 {
            get {
                return ResourceManager.GetString("FieldValPin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh Snap!, Error happen, please try again later.
        /// </summary>
        internal static string FormErrMsg {
            get {
                return ResourceManager.GetString("FormErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &apos;by invitation&apos; only site, you need an invitation code to register..
        /// </summary>
        internal static string InvitationDesc {
            get {
                return ResourceManager.GetString("InvitationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has been send!.
        /// </summary>
        internal static string InvitationSuccessMsg {
            get {
                return ResourceManager.GetString("InvitationSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to invite a friend, go ahead!.
        /// </summary>
        internal static string InviteFriendText {
            get {
                return ResourceManager.GetString("InviteFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 FIFA World Cup.
        /// </summary>
        internal static string Link1Text {
            get {
                return ResourceManager.GetString("Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fifa.com/index.html.
        /// </summary>
        internal static string Link1Url {
            get {
                return ResourceManager.GetString("Link1Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA World Cup | EA SPORTS.
        /// </summary>
        internal static string Link2Text {
            get {
                return ResourceManager.GetString("Link2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.easports.com/2014-fifa-world-cup.
        /// </summary>
        internal static string Link2Url {
            get {
                return ResourceManager.GetString("Link2Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string LinksTitle {
            get {
                return ResourceManager.GetString("LinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your scores have been submitted successfully..
        /// </summary>
        internal static string MatchSubmitted {
            get {
                return ResourceManager.GetString("MatchSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MnuChat {
            get {
                return ResourceManager.GetString("MnuChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Scores.
        /// </summary>
        internal static string MnuMatches {
            get {
                return ResourceManager.GetString("MnuMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string MnuParticipants {
            get {
                return ResourceManager.GetString("MnuParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string MnuReg {
            get {
                return ResourceManager.GetString("MnuReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string MnuRules {
            get {
                return ResourceManager.GetString("MnuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string NewUserTitle {
            get {
                return ResourceManager.GetString("NewUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of participants who already submitted their scores..
        /// </summary>
        internal static string ParticipantDesc {
            get {
                return ResourceManager.GetString("ParticipantDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only people that have submitted their scores and donated will show. List is order by number of points accumulated in descending order..
        /// </summary>
        internal static string ParticipantNode {
            get {
                return ResourceManager.GetString("ParticipantNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif.
        /// </summary>
        internal static string PayPalButton {
            get {
                return ResourceManager.GetString("PayPalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM3NTSGGXKBWJ.
        /// </summary>
        internal static string PayPalFormCode {
            get {
                return ResourceManager.GetString("PayPalFormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify..
        /// </summary>
        internal static string PleaseVerify {
            get {
                return ResourceManager.GetString("PleaseVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our privacy commitments are fundamental to the way we do business. These apply to everyone who has a relationship with us and Web site visitors..
        /// </summary>
        internal static string PrivacyMsg {
            get {
                return ResourceManager.GetString("PrivacyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will protect your privacy and keep your personal information safe. .
        /// </summary>
        internal static string PrivacyMsg1 {
            get {
                return ResourceManager.GetString("PrivacyMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will not sell your personal information to anyone, for any purpose. Period..
        /// </summary>
        internal static string PrivacyMsg2 {
            get {
                return ResourceManager.GetString("PrivacyMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will fully disclose our privacy policy in plain language, and make our policy easily accessible to you..
        /// </summary>
        internal static string PrivacyMsg3 {
            get {
                return ResourceManager.GetString("PrivacyMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will notify you of revisions to our privacy policy, in advance. No surprises..
        /// </summary>
        internal static string PrivacyMsg4 {
            get {
                return ResourceManager.GetString("PrivacyMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to hear from you. You can send us questions or feedback on our privacy policy..
        /// </summary>
        internal static string PrivacyMsg5 {
            get {
                return ResourceManager.GetString("PrivacyMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivatePolicyTitle {
            get {
                return ResourceManager.GetString("PrivatePolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh Snap!, Error happen, please review your inviation code.
        /// </summary>
        internal static string RegFailMsg {
            get {
                return ResourceManager.GetString("RegFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration fail, user already exists..
        /// </summary>
        internal static string RegFormFail {
            get {
                return ResourceManager.GetString("RegFormFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Welcome to 2014 FIFA Pool&lt;/h1&gt;&lt;br&gt;&lt;br&gt;Your can now load your match scores in our site, use your email and PIN to sign in the site, then go to the [My Scores] menu option.&lt;br/&gt;&lt;br/&gt;Go to &lt;b&gt;&lt;a href=&apos;{0}&apos; &gt;http://laquiniela.Info&lt;/a&gt;&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;Good luck!.
        /// </summary>
        internal static string RegFormMessage {
            get {
                return ResourceManager.GetString("RegFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to 2014 FIFA Pool.
        /// </summary>
        internal static string RegFormSubjet {
            get {
                return ResourceManager.GetString("RegFormSubjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration has been processed, you will get and email shortly.
        /// </summary>
        internal static string RegFormSuccess {
            get {
                return ResourceManager.GetString("RegFormSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation code or Email address are not valid, please verify..
        /// </summary>
        internal static string RegInvalidCodeMsg {
            get {
                return ResourceManager.GetString("RegInvalidCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration form submitted!.
        /// </summary>
        internal static string RegSuccessMsg {
            get {
                return ResourceManager.GetString("RegSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be in touch soon..
        /// </summary>
        internal static string RegSuccessMsg1 {
            get {
                return ResourceManager.GetString("RegSuccessMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every participant should &lt;a class=&apos;{0}&apos; href=&apos;{1}&apos;&gt;register&lt;/a&gt; using an invitation code, that will be send to him..
        /// </summary>
        internal static string Rules1 {
            get {
                return ResourceManager.GetString("Rules1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT! Only individuals who submit their scores before June 11th will participate in the pool..
        /// </summary>
        internal static string Rules10 {
            get {
                return ResourceManager.GetString("Rules10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The official score for each match will be the one at the end of the match, including extra time, and/or series of penalties..
        /// </summary>
        internal static string Rules11 {
            get {
                return ResourceManager.GetString("Rules11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of points per match is 3:.
        /// </summary>
        internal static string Rules12 {
            get {
                return ResourceManager.GetString("Rules12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 points if you guess the match score, and.
        /// </summary>
        internal static string Rules13 {
            get {
                return ResourceManager.GetString("Rules13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 point if one of the following happen: if you guess the winner or if you guess a draw..
        /// </summary>
        internal static string Rules14 {
            get {
                return ResourceManager.GetString("Rules14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winner of the pool, will be the person with the higher number of points accumulated at the end of the tournament..
        /// </summary>
        internal static string Rules15 {
            get {
                return ResourceManager.GetString("Rules15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If more than one, prize will be equally divided between winners..
        /// </summary>
        internal static string Rules16 {
            get {
                return ResourceManager.GetString("Rules16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A donation is require to participate in the pool.
        /// </summary>
        internal static string Rules17 {
            get {
                return ResourceManager.GetString("Rules17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations are taken via PayPal for the fix amount of {0}.
        /// </summary>
        internal static string Rules18 {
            get {
                return ResourceManager.GetString("Rules18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal will charge a &lt;a class=&apos;{0}&apos; href=&apos;https://www.paypal.com/us/webapps/mpp/merchant-fees&apos; target=&apos;_top&apos;&gt;commission&lt;/a&gt; of 2.9% + $0.30 per transaction, that will be deducted from the donation.
        /// </summary>
        internal static string Rules19 {
            get {
                return ResourceManager.GetString("Rules19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After registration you can go to &lt;a class=&apos;{0}&apos; href=&apos;{1}&apos;&gt;{2}&lt;/a&gt; and enter your estimated scores per match..
        /// </summary>
        internal static string Rules2 {
            get {
                return ResourceManager.GetString("Rules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 15% commission of the total pool will be charged by the [laquiniela.info] Site for services provided, at the end of the tournament..
        /// </summary>
        internal static string Rules20 {
            get {
                return ResourceManager.GetString("Rules20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest of the donation will be accumulated and given to the person with the higher number of points accumulated at the end of the tournament..
        /// </summary>
        internal static string Rules21 {
            get {
                return ResourceManager.GetString("Rules21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize will be transfered to winner via PayPal, Mailed Check or Cash if winner is easy to contact..
        /// </summary>
        internal static string Rules22 {
            get {
                return ResourceManager.GetString("Rules22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can store your scores at any time using the &apos;Save ...&apos; button located in the bottom left corner of the &lt;a class=&apos;{0}&apos; href=&apos;{1}&apos;&gt;{2}&lt;/a&gt; page..
        /// </summary>
        internal static string Rules3 {
            get {
                return ResourceManager.GetString("Rules3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are ready, you can submit your scores to enter the pool, use the  &apos;Submit ...&apos; button at the end of the &lt;a class=&apos;{0}&apos; href=&apos;{1}&apos;&gt;{2}&lt;/a&gt; page..
        /// </summary>
        internal static string Rules4 {
            get {
                return ResourceManager.GetString("Rules4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores are submitted to the pool in two occasions:.
        /// </summary>
        internal static string Rules5 {
            get {
                return ResourceManager.GetString("Rules5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First round, Group eliminations  - &lt;i&gt;Right now and until June 11th&lt;/i&gt;.
        /// </summary>
        internal static string Rules6 {
            get {
                return ResourceManager.GetString("Rules6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second round, Final eliminations - &lt;i&gt;when matches are determined (after June 26th)&lt;/i&gt;.
        /// </summary>
        internal static string Rules7 {
            get {
                return ResourceManager.GetString("Rules7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the scores are submitted you will NOT be able to change them anymore..
        /// </summary>
        internal static string Rules8 {
            get {
                return ResourceManager.GetString("Rules8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A donation is required to submit your scores, see &lt;a class=&apos;{0}&apos; href=&apos;#&apos;&gt;Donantions&lt;/a&gt; below for more details..
        /// </summary>
        internal static string Rules9 {
            get {
                return ResourceManager.GetString("Rules9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string RulesTitle {
            get {
                return ResourceManager.GetString("RulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        internal static string SendFeedbackMsg {
            get {
                return ResourceManager.GetString("SendFeedbackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to join a FIFA World Cup 2014 Pool, this site is by invitation only, and you need an invitation code to register.&lt;br&gt;&lt;br&gt;Here is your code &lt;b&gt;{0}&lt;/b&gt; to register and participate in a FIFA World Cup 2014 Pool, go to &lt;b&gt;&lt;a href=&apos;{1}&apos; &gt;http://laquiniela.info&lt;/a&gt;&lt;/b&gt; and select the option for [Register]&lt;br/&gt;&lt;br/&gt;And take some time to check the Rules of the pool.&lt;br/&gt;&lt;br/&gt;Have fun!.
        /// </summary>
        internal static string SendInviteMessage {
            get {
                return ResourceManager.GetString("SendInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, sent you an invitation to join a FIFA World Cup 2014 Pool.
        /// </summary>
        internal static string SendInviteSubject {
            get {
                return ResourceManager.GetString("SendInviteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFAWorld Cup Brazil.
        /// </summary>
        internal static string SiteSubtitle {
            get {
                return ResourceManager.GetString("SiteSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A donation of {0} needs to be made, for you to participation in this Quiniela, if you are not sure, please read more details from our .
        /// </summary>
        internal static string SSModalBullet1 {
            get {
                return ResourceManager.GetString("SSModalBullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure email address for payment is the same as your registration, so we can verify the donation..
        /// </summary>
        internal static string SSModalBullet2 {
            get {
                return ResourceManager.GetString("SSModalBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would save your scores and process your donation via a secure connection via Paypal.
        /// </summary>
        internal static string SSModalBullet3 {
            get {
                return ResourceManager.GetString("SSModalBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once donation is cleared, you&apos;ll be redirected back to this site..
        /// </summary>
        internal static string SSModalBullet4 {
            get {
                return ResourceManager.GetString("SSModalBullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then you&apos;ll be formally added as a participant..
        /// </summary>
        internal static string SSModalBullet5 {
            get {
                return ResourceManager.GetString("SSModalBullet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal - The safer, easier way to pay online!.
        /// </summary>
        internal static string SSModalPayPalToolTip {
            get {
                return ResourceManager.GetString("SSModalPayPalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make note of the following:.
        /// </summary>
        internal static string SSModalSubTitle {
            get {
                return ResourceManager.GetString("SSModalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your final scores.
        /// </summary>
        internal static string SSModalTitle {
            get {
                return ResourceManager.GetString("SSModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string SSModalWarning {
            get {
                return ResourceManager.GetString("SSModalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the scores are submited, you will not be able to change them anymore..
        /// </summary>
        internal static string SSModalWarningTxt {
            get {
                return ResourceManager.GetString("SSModalWarningTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 Pool.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the person with a higher number of points.
        /// </summary>
        internal static string TopWinDesc {
            get {
                return ResourceManager.GetString("TopWinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Winner Name Here].
        /// </summary>
        internal static string TopWinner {
            get {
                return ResourceManager.GetString("TopWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This amount represents the total accumulated from all participants (commisions already applied)..
        /// </summary>
        internal static string TopWinPrizeDesc {
            get {
                return ResourceManager.GetString("TopWinPrizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Winner.
        /// </summary>
        internal static string TopWinTitle {
            get {
                return ResourceManager.GetString("TopWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants, sorted by points.
        /// </summary>
        internal static string UserListTitle {
            get {
                return ResourceManager.GetString("UserListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logged in!.
        /// </summary>
        internal static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Log-in Fail!.
        /// </summary>
        internal static string UserLoginFail {
            get {
                return ResourceManager.GetString("UserLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! {0}.
        /// </summary>
        internal static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner Prize.
        /// </summary>
        internal static string WinnerPrize {
            get {
                return ResourceManager.GetString("WinnerPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string WinnerTitle {
            get {
                return ResourceManager.GetString("WinnerTitle", resourceCulture);
            }
        }
    }
}
